const $ = (id) => document.getElementById(id);
const map = L.map('map', {zoomControl:false}).setView([37.764,-122.44], 12);
L.control.zoom({position:'bottomright'}).addTo(map);
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {maxZoom:19, attribution:'&copy; OpenStreetMap'}).addTo(map);
let sourceLayer, resultLayer, markerLayers=[], currentRun=null, polling=false, activeDataset='';
const datasetNames={};let datasetLoadRevision=0, datasetLoading=true, analysisEnabled=false, workerReady=false, runActive=false, resultMapRevision=0;
const ACCESS_KEY='geoscope_access_key';
const candidateInputs=[['candidate-a-lon','candidate-a-lat'],['candidate-b-lon','candidate-b-lat']];
function coordinates(index){return candidateInputs[index].map(id=>Number($(id).value))}
function setCoordinates(index,lon,lat){$(candidateInputs[index][0]).value=lon;$(candidateInputs[index][1]).value=lat}
function validCoord(p){return p.every(Number.isFinite)&&p[0]>=-180&&p[0]<=180&&p[1]>=-90&&p[1]<=90}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function propsLayer(f){return f.properties?.layer==='park'?'service':f.properties?.layer}
function styleFor(f){const role=propsLayer(f);if(role==='zone')return{color:'#c08046',weight:1.4,fillColor:'#e5ad71',fillOpacity:.25};if(role==='service')return{color:'#559365',weight:1.2,fillColor:'#83b88b',fillOpacity:.65};return{color:'#789d98',weight:.7,fillColor:'#a7c8bf',fillOpacity:.18}}
function pointStyle(f){const role=propsLayer(f);return{radius:6,color:role==='service'?'#559365':'#648d83',weight:1,fillOpacity:.55,fillColor:role==='service'?'#83b88b':'#a7c8bf'}}
function featurePopup(f){const p=f.properties||{};let detail=propsLayer(f)==='population'?`${Number(p.population||0).toLocaleString()} population estimate`:propsLayer(f)==='zone'?'Analysis zone':'Service location';return `<div class="tract-popup"><b>${escapeHtml(p.name||p.geoid||p.id||'Feature')}</b><br>${detail}</div>`}
function candidateIcon(letter,kind){return L.divIcon({className:'',html:`<div class="candidate-marker ${kind}">${letter}</div>`,iconSize:[25,25],iconAnchor:[12,12]})}
function clearResults(){resultMapRevision++;if(resultLayer){map.removeLayer(resultLayer);resultLayer=null}$('result-panel').classList.add('hidden');$('summary').textContent='';$('metrics').innerHTML='';$('downloads').innerHTML='';$('logs').innerHTML='';$('caveats').innerHTML=''}
function updateRunButton(){if($('run-button'))$('run-button').disabled=datasetLoading||runActive||!analysisEnabled||!workerReady}
function placeCandidates(){markerLayers.forEach(m=>map.removeLayer(m));markerLayers=[];if($('analysis-mode').value!=='compare')return;for(const [i,letter,kind] of [[0,'A','a'],[1,'B','b']]){const p=coordinates(i);if(!validCoord(p))continue;const marker=L.marker([p[1],p[0]],{icon:candidateIcon(letter,kind),draggable:true}).addTo(map).bindTooltip(`Candidate ${letter} · illustrative; drag to adjust`);marker.on('dragend',e=>{const ll=e.target.getLatLng();setCoordinates(i,ll.lng.toFixed(5),ll.lat.toFixed(5))});markerLayers.push(marker)}}
function mapData(data){const display={type:'FeatureCollection',features:data.features.filter(f=>propsLayer(f)!=='population'||Number(f.properties?.population)>0)};if(sourceLayer)map.removeLayer(sourceLayer);sourceLayer=L.geoJSON(display,{style:styleFor,pointToLayer:(f,ll)=>L.circleMarker(ll,pointStyle(f)),onEachFeature:(f,l)=>l.bindPopup(featurePopup(f))}).addTo(map);const roles={population:0,service:0,zone:0};for(const f of data.features)if(roles[propsLayer(f)]!==undefined)roles[propsLayer(f)]++;$('feature-count').textContent=`${roles.population} population areas · ${roles.service} services · ${roles.zone} zones`;if(activeDataset==='sf2020')map.fitBounds([[37.70,-122.53],[37.83,-122.35]]);else if(sourceLayer.getBounds().isValid())map.fitBounds(sourceLayer.getBounds().pad(.08));$('analysis-mode').querySelector('option[value="access"]').disabled=!roles.service;$('analysis-mode').querySelector('option[value="compare"]').disabled=!roles.service;$('analysis-mode').querySelector('option[value="exposure"]').disabled=!roles.zone;if($('analysis-mode').selectedOptions[0].disabled)$('analysis-mode').value=roles.service?'access':'exposure';updateMode()}
async function loadDataset(id){activeDataset=id;datasetLoading=true;updateRunButton();const revision=++datasetLoadRevision;clearResults();try{let url=id==='demo'?'/api/datasets/demo':id==='sf2020'?'/api/datasets/real':`/api/datasets/${encodeURIComponent(id)}`;const response=await fetch(url);if(!response.ok)throw Error('Dataset could not be loaded.');const data=await response.json();if(revision!==datasetLoadRevision||id!==$('dataset').value)return;mapData(data);if(id==='sf2020'){$('map-title').textContent='San Francisco · 2020 Census + selected parks';setCoordinates(0,-122.43,37.77);setCoordinates(1,-122.42,37.76);$('threshold').value=400;$('source-note').innerHTML='2020 Census TIGERweb POP100 + selected parks inventory. Candidate coordinates are illustrative; inventory coverage has documented limits. <a href="/api/source-manifest" target="_blank" rel="noreferrer">Source dataset ↗</a>'}else if(id==='demo'){$('map-title').textContent='Harborview · synthetic fixture';setCoordinates(0,-122.331,47.612);setCoordinates(1,-122.316,47.615);$('threshold').value=400;$('source-note').textContent='Fabricated features for demonstration and testing. They do not describe a real neighborhood.'}else{$('map-title').textContent=datasetNames[id]||'Uploaded GeoJSON';$('source-note').textContent='User supplied EPSG:4326 GeoJSON. Feature roles and population field were validated.'}placeCandidates()}finally{if(revision===datasetLoadRevision){datasetLoading=false;updateRunButton()}}}
function updateMode(){const mode=$('analysis-mode').value;const compare=mode==='compare';$('candidate-controls').classList.toggle('hidden',!compare);$('candidate-legend').classList.toggle('hidden',!compare);$('threshold-group').classList.toggle('hidden',mode==='exposure');$('distance-type').classList.toggle('hidden',mode==='exposure');const q={access:'Which population areas are farthest from the nearest service, and how many residents are within 400 meters?',compare:'Which candidate serves more residents within 400 meters, and how much does each reduce average distance?',exposure:'How many residents live in the supplied zones, and what share of the study population is inside?'};if(!$('question').dataset.edited)$('question').value=q[mode];placeCandidates()}
async function init(){const c=await(await fetch('/api/config')).json();const ds=$('dataset');ds.innerHTML='';if(c.real){ds.add(new Option('San Francisco · 2020 Census + parks','sf2020'));datasetNames.sf2020=c.real.name}ds.add(new Option('Harborview · synthetic fixture','demo'));datasetNames.demo=c.demo.name;if(!c.real)$('source-note').textContent=c.source_note;if(c.real)$('source-note').innerHTML='San Francisco 2020 Census population + selected parks inventory. <a href="/api/source-manifest" target="_blank" rel="noreferrer">Open source manifest ↗</a>';if(c.real)await loadDataset('sf2020');else await loadDataset('demo');const worker=await(await fetch('/api/worker-status')).json();$('worker-label').textContent=worker.ok?'WORKER READY':'WORKER UNAVAILABLE';$('worker-label').title=worker.message||'';$('worker-label').previousElementSibling.style.background=worker.ok?'#70aa75':'#cc7c3a';analysisEnabled=c.analysis_enabled;workerReady=worker.ok===true;updateRunButton();$('run-button').title=analysisEnabled?(workerReady?'':'Isolated worker is not ready'):'Analysis services are not configured on this installation.';const key=sessionStorage.getItem(ACCESS_KEY);if(key)$('access-key').value=key;updateMode()}
$('dataset').addEventListener('change',e=>loadDataset(e.target.value).catch(error=>{datasetLoading=false;updateRunButton();alert(error.message)}));
$('analysis-mode').addEventListener('change',updateMode);
$('question').addEventListener('input',()=>{$('question').dataset.edited='true'});
$('access-key').addEventListener('input',()=>sessionStorage.setItem(ACCESS_KEY,$('access-key').value.trim()));
$('upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const body=new FormData();body.append('file',file);try{const token=$('access-key').value.trim();const response=await fetch('/api/datasets',{method:'POST',headers:{'Authorization':`Bearer ${token}`},body});const uploaded=await response.json();if(!response.ok)throw Error(typeof uploaded.detail==='string'?uploaded.detail:'Upload failed');datasetNames[uploaded.id]=file.name;const option=new Option(`${file.name} · uploaded`,uploaded.id);$('dataset').add(option);$('dataset').value=uploaded.id;await loadDataset(uploaded.id);const mode=$('analysis-mode');if(!uploaded.schema.zone_features&&uploaded.schema.service_features)mode.value='access';if(!uploaded.schema.service_features&&uploaded.schema.zone_features)mode.value='exposure';updateMode();alert(`Dataset ready: ${uploaded.schema.population_features} population features, ${uploaded.schema.service_features} services, ${uploaded.schema.zone_features} zones. Use a numeric population property and layer=population/service/zone. Legacy layer=park is accepted as service.`)}catch(err){alert(err.message)}});
candidateInputs.flat().forEach(id=>$(id).addEventListener('input',placeCandidates));
$('run-button').addEventListener('click',async()=>{const token=$('access-key').value.trim();if(!token){$('access-key').focus();return}const mode=$('analysis-mode').value;const body={dataset_id:activeDataset,analysis_mode:mode,question:$('question').value,threshold_m:Number($('threshold').value)};if(mode==='compare'){body.candidate_a=coordinates(0);body.candidate_b=coordinates(1);if(!validCoord(body.candidate_a)||!validCoord(body.candidate_b)){alert('Enter candidate coordinates within EPSG:4326 bounds.');return}}clearResults();runActive=true;$('dataset').disabled=true;$('analysis-mode').disabled=true;$('upload').disabled=true;updateRunButton();$('run-button').querySelector('span:nth-child(2)').textContent='Starting…';$('result-panel').classList.remove('hidden');$('result-status').textContent='Starting';$('result-status').className='status-pill';try{const response=await fetch('/api/runs',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:'Could not start run');currentRun=data.id;pollRun(token)}catch(err){$('result-status').textContent='Not started';$('result-status').className='status-pill failed';$('summary').textContent=err.message;$('dataset').disabled=false;$('analysis-mode').disabled=false;$('upload').disabled=false;runActive=false;updateRunButton();$('run-button').querySelector('span:nth-child(2)').textContent='Run the analysis'}});
async function pollRun(token){if(polling)return;polling=true;while(currentRun){try{const response=await fetch(`/api/runs/${currentRun}`,{headers:{'Authorization':`Bearer ${token}`}});const run=await response.json();renderRun(run,token);if(['completed','failed','interrupted'].includes(run.status)){currentRun=null;break}}catch{}await new Promise(resolve=>setTimeout(resolve,1500))}polling=false;runActive=false;$('dataset').disabled=false;$('analysis-mode').disabled=false;$('upload').disabled=false;updateRunButton();$('run-button').querySelector('span:nth-child(2)').textContent='Run the analysis'}
function metricCard(value,label){return `<div class="metric"><div class="value">${escapeHtml(value)}</div><div class="label">${escapeHtml(label)}</div></div>`}
function renderRun(r,token){$('result-panel').classList.remove('hidden');$('result-status').textContent=r.status;$('result-status').className='status-pill'+(['failed','interrupted'].includes(r.status)?' failed':'');$('summary').textContent=r.summary||r.error||'The agent is working through the analysis steps.';$('result-title').textContent=r.status==='failed'?'Run stopped':({'access':'Service access',compare:'Candidate comparison',exposure:'Population inside zones'}[r.analysis_mode]||'GIS analysis');if(r.result){const m=r.result.metrics||{};const showN=x=>x==null?'N/A':Number(x).toLocaleString(),showM=x=>x==null?'N/A':`${Number(x).toFixed(0)} m`;let cards=[];if(r.analysis_mode==='exposure'){cards=[metricCard(showN(m.inside_population),'population assigned inside supplied zones'),metricCard(m.share_inside_pct==null?'N/A':`${Number(m.share_inside_pct).toFixed(1)}%`,'share of total population'),metricCard(showN(m.outside_population),'population assigned outside zones')]}else if(r.analysis_mode==='compare'){cards=[metricCard(showN(m.candidate_a?.newly_served_population),'A · newly served'),metricCard(showN(m.candidate_b?.newly_served_population),'B · newly served'),metricCard(r.result.comparison?.preferred_candidate||'Tie','preferred by newly served population')]}else{cards=[metricCard(showN(m.baseline?.served_population),'population within threshold'),metricCard(showN(m.baseline?.underserved_population),'population beyond threshold'),metricCard(showM(m.baseline?.weighted_mean_nearest_m),'weighted mean distance')]}
$('metrics').innerHTML=cards.join('');$('plan').textContent=r.plan||'';$('caveats').innerHTML='<li>Metrics and per-feature results matched a fixed GIS reference calculation.</li><li>Distances are straight-line; population polygon representative points are a proxy.</li><li>'+(r.analysis_mode==='exposure'?'The whole population estimate for each polygon is assigned according to its representative point; this is not an exact resident count inside the zone.':r.analysis_mode==='compare'?'Candidate ranking uses newly served population within the threshold; sites are illustrative, not feasibility recommendations.':'Population proximity is not a walking route or a measure of actual access.')+'</li><li>'+(r.synthetic?'Synthetic fixture only; not real-world evidence.':`Source: ${escapeHtml(r.dataset_name)}.`)+'</li>';$('downloads').innerHTML=['analysis.py','result.json','result.geojson','request.json','trace.json',...(r.attempts||[]).map(a=>a.script_file)].filter((n,i,a)=>n&&a.indexOf(n)===i).map(n=>`<button class="download-link" data-file="${n}">${n} ↓</button>`).join('');$('downloads').querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>downloadArtifact(r.id,button.dataset.file,token)));const mapRevision=++resultMapRevision;fetch(`/api/runs/${r.id}/map`,{headers:{'Authorization':`Bearer ${token}`}}).then(x=>x.ok?x.json():null).then(data=>{if(!data||mapRevision!==resultMapRevision)return;if(resultLayer)map.removeLayer(resultLayer);resultLayer=L.geoJSON(data,{style:f=>({color:'#477f92',weight:1,fillColor:f.properties.inside_zone?'#dfaa86':f.properties.underserved?'#dfaa86':'#77a879',fillOpacity:.35}),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:5,color:'#477f92',fillOpacity:.7})}).addTo(map)}).catch(()=>{})}const logs=r.logs||[];$('logs').innerHTML=logs.map(l=>`<div class="log-row"><b>${escapeHtml((l.status||'step').toUpperCase())}</b> · ${escapeHtml(l.text)}</div>`).join('');$('logs').scrollTop=$('logs').scrollHeight}
async function downloadArtifact(runId,name,token){try{const response=await fetch(`/api/runs/${runId}/artifacts/${name}`,{headers:{'Authorization':`Bearer ${token}`}});if(!response.ok)throw Error(`Download failed (${response.status}).`);const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.position='fixed';a.style.left='-10000px';document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(error){const notice=document.createElement('span');notice.className='download-error';notice.textContent=`${name}: ${error.message||'download failed'}`;$('downloads').appendChild(notice)}}
init().catch(e=>{$('worker-label').textContent='SERVICE STATUS UNKNOWN';console.error(e)});
